### ISSUE TITLE
No events generated

### ISSUE THREAD

**Issue by codesftdev** [Loloppe/Lolighter#3]
For some reason, no notes are generated/modified/removed when saved

**Comment by Loloppe** [comment]
Lolighter is pretty old, I would recommend using the AutoMapper plugin for ChroMapper instead. You can find it on GitHub or in the CM Discord.
Anyway idk, when you save, it should generate a bunch of new files (if I remember correctly, I haven't used that program in years) and open a File Explorer to the directory with the new files.
Also, make sure you press Light, then the 2-3 popups, before saving. This program use Notes to generates Lights, so your map must be mapped already before using the light generator.
